---
- name: Test role
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - debug:
        msg:
        - "ansible_os_family: {{ ansible_os_family }}"
        - "ansible_distribution: {{ ansible_distribution }}"
        - "ansible_distribution_version {{ ansible_distribution_version }}"
        - "ansible_distribution_major_version: {{ ansible_distribution_major_version | default() }}"
        - "ansible_distribution_minor_version: {{ ansible_distribution_minor_version | default() }}"
        - "ansible_pkg_mgr: {{ ansible_pkg_mgr }}"
